
module.exports = {
  USER: 'LLJ_USER',
  BALANCE: 'LLJ_BALANCE',
  POINTS: 'LLJ_POINTS',
  MEMBER_LEVEL: 'LLJ_MEMBER_LEVEL',
  TOTAL_RECHARGE: 'LLJ_TOTAL_RECHARGE',
  ADDRESS: 'LLJ_ADDRESS',
  ORDER_STATS: 'LLJ_ORDER_STATS',

  CART_CLEAR: 'LLJ_CART_CLEAR',
  ORDER_MODE: 'LLJ_ORDER_MODE',
  TRADE_TAB: 'LLJ_TRADE_TAB',
  LOC_CACHE: 'LLJ_LOC_CACHE',

  POINTS_GIFTS_CACHE: 'LLJ_POINTS_GIFTS_CACHE',
  POINTS_GIFTS_CACHE_AT: 'LLJ_POINTS_GIFTS_CACHE_AT',

  SHOP_CONTACT_CACHE_MAIN: 'shop_contact_cache_main_v1',
  SHOP_CONFIG_CACHE_MAIN: 'shop_config_cache_main_v1',

  IS_MERCHANT: 'IS_MERCHANT_V1',
  MERCHANT_SESSION: 'merchant_session_v1',
  PRINTER_FLOAT_POS: 'LLJ_PRINTER_FLOAT_POS_V1',
};
